# Теория
Мы хотим разного поведения в зависимости от типа ошибки и окружения. Например, приложение должно падать если это микросервис выполняющийся в кластере контейнеров (в этом случае средства оркестрации ответственны за перенаправление трафика на рабочую копию приложения, реакцию на ошибку и прочее). Или приложение должно логгировать ошибки связанные с сетевым взаимодействием и возвращать клиенту ошибки связанные с валидацией сообщения. И так далее.

В общем, не существует лучших практик для обработки ошибок. Разработчик самостоятельно решает как поступать в том или ином случае под каждое свое приложение.

# Обработка ошибок в bishop
Из коробки, библиотека будет падать при возникновении системных ошибок (пример: несуществующая функция) и возвращать пользовательские ошибки (пример: сервис вызвал `throw new Error('some custom error')`).

Поведение при возникновении ошибки задается при инициализации библиотеки свойством `.terminateOn`. В этом свойстве мы передаем названия ошибок при которых приложение должно падать, либо функцию-обработчик ошибок.

В node.js название ошибки определяется свойством `.name`. К примеру, следующий код создаст ошибку CustomError:
```javascript
const err = new Error('some error message')
err.name = 'CustomError'
throw err
```
Вопрос создания кастомных ошибок в nodejs более комплексный чем код выше (надо правильно передавать stacktrace и т.п.), поэтому в продакшн-системах рекомендуется использовать для этого специализированные модули. Пример такого модуля приведен в разделе "Ссылки".


# Примеры

Приложение должно упасть если код вызовет ошибку через `throw new Error()`
```javascript
const bisop = require('bishop')({
  terminateOn: ['Error']
})
```

Приложение выведет в консоль ошибку "test error" и вернет остальные клиенту
```javascript
const bisop = require('bishop')({
  terminateOn: err => {
    if (err.message === 'test error') {
      console.log(err)
      return false // mute error
    }
    // emit this error as usual (return to sender, etc)
    return true
  }
})
```


# Задача
Добавьте в `math.js` проверку на переданые значение. Ваш код должен бросать ошибку 'ValidationError' если передано не число. После этого, создайте обработчик ошибок который выводит "not a number" и выйдет с кодом 12 (указание на `process.exit`).



# Ссылки
* https://nodejs.org/api/errors.html - официальная документация по работе с ошибками
* https://github.com/shutterstock/node-common-errors - пример модуля для создания собственных ошибок
